query appSettings_getAppSettings(
  $skip: Int
  $take: Int
  $where: AppSettingsFilterInput
  $order: [AppSettingsSortInput!]
) {
  appSettings_getAppSettings {
    result(skip: $skip, take: $take, where: $where, order: $order) {
      items {
        createdDate
        id
        privacyPolicy
        termsAndConditions
        shippingCost
      }
      pageInfo {
        hasNextPage
        hasPreviousPage
      }
      totalCount
    }
    status
  }
}
