query customizedExercise_getCustomizedExercise($exerciseId: Int!) {
  customizedExercise_getCustomizedExercise(exerciseId: $exerciseId) {
    result {
      note
      reps
      hold
      holdType
      set
      perform
      performType
      userId
      exerciseId
      id
      isDeleted
      createdDate
      lastModifiedDate
    }
    status
  }
}
